# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-14 05:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(blank=True, max_length=200, null=True, unique=True, verbose_name='Name in English')),
                ('name_uk', models.CharField(blank=True, max_length=200, null=True, unique=True, verbose_name='Name in Ukrainian')),
                ('name_ru', models.CharField(blank=True, max_length=200, null=True, unique=True, verbose_name='Name in Russian')),
                ('biography_en', models.TextField(blank=True, null=True, verbose_name='Biography in English')),
                ('biography_uk', models.TextField(blank=True, null=True, verbose_name='Biography in Ukrainian')),
                ('biography_ru', models.TextField(blank=True, null=True, verbose_name='Biography in Russian')),
            ],
            options={
                'verbose_name': 'Author',
                'verbose_name_plural': 'Authors',
            },
        ),
        migrations.CreateModel(
            name='Phrases',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phrase_en', models.TextField(blank=True, null=True, verbose_name='Phrase in English')),
                ('phrase_uk', models.TextField(blank=True, null=True, verbose_name='Phrase in Ukrainian')),
                ('phrase_ru', models.TextField(blank=True, null=True, verbose_name='Phrase in Russian')),
                ('showed', models.BooleanField(default=False)),
                ('phrase_status', models.CharField(choices=[('published', 'Published'), ('draft', 'Draft'), ('unpublished', 'Unpublished')], default='published', max_length=11, verbose_name='Status')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Date published')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='philosophy_phrases.Author', verbose_name='Author')),
            ],
            options={
                'verbose_name': 'Phrase',
                'verbose_name_plural': 'Phrases',
            },
        ),
        migrations.CreateModel(
            name='PhraseSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('on', 'Enabled'), ('off', 'Disabled')], default='on', max_length=10, verbose_name='Status')),
                ('lang_detect', models.CharField(choices=[('en', 'English'), ('uk', 'Ukrainian'), ('ru', 'Russian'), ('auto', 'Auto')], default='auto', max_length=10, verbose_name='Language of phrases')),
                ('background_color', models.CharField(default='383636', max_length=6, verbose_name='Background color of window')),
                ('phrase_color', models.CharField(default='bdefac', max_length=6, verbose_name='Phrase text color')),
                ('author_color', models.CharField(default='21ff00', max_length=6, verbose_name='Author text color')),
            ],
            options={
                'verbose_name': 'Phrases settings',
                'verbose_name_plural': 'Phrases settings',
            },
        ),
    ]
